name: release-build

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  release:
    types:
      - created

jobs:
  build-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn make
    - run: ls out/make/deb/x64/
    - run: ls out/make/rpm/x64/
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'out/make/deb/x64/*.deb'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'out/make/rpm/x64/*.rpm'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

 
#  build-mac:
#    runs-on: macos-latest
#    needs: build-linux
    
#    strategy:
#      matrix:
#        node-version: [12.x]

#    steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - run: yarn
#    - run: yarn make
